ARG AIRFLOW_VERSION=${AIRFLOW_VERSION}
FROM apache/airflow:${AIRFLOW_VERSION}

ARG AIRFLOW_VERSION_LIB
ARG PYSPARK_VERSION_LIB
ARG MARIADB_JDBC_URL_LIB

USER root
ENV AIRFLOW_VERSION_LIB=${AIRFLOW_VERSION_LIB} \
    PYSPARK_VERSION_LIB=${PYSPARK_VERSION_LIB} \
    MARIADB_JDBC_URL_LIB=${MARIADB_JDBC_URL_LIB} \
    JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 \
    SPARK_HOME=/opt/spark
ENV PATH=$JAVA_HOME/bin:$SPARK_HOME/bin:$PATH

RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-17-jdk-headless curl netcat-openbsd mariadb-client && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/spark/jars && \
    curl -fL -o /opt/spark/jars/mariadb-java-client.jar "${MARIADB_JDBC_URL_LIB}"

USER airflow
RUN pip install --no-cache-dir \
    pyspark==${PYSPARK_VERSION_LIB} pandas minio requests \
    apache-airflow==${AIRFLOW_VERSION_LIB} \
    apache-airflow-providers-apache-spark \
    apache-airflow-providers-mysql \
    apache-airflow-providers-redis python-dotenv

USER root
RUN mkdir -p /opt/airflow/dags /opt/airflow/logs /opt/airflow/plugins && chmod -R 777 /opt/airflow
COPY entrypoint-airflow.sh /entrypoint-airflow.sh
RUN chmod +x /entrypoint-airflow.sh && groupadd -for -g 984 docker && usermod -aG docker airflow

USER airflow
WORKDIR /opt/airflow
ENTRYPOINT ["/entrypoint-airflow.sh"]